# Generated by Django 2.1.1 on 2018-09-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('w', models.IntegerField()),
                ('h', models.IntegerField()),
            ],
        ),
    ]
