# Generated by Django 2.1.1 on 2018-09-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campip', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cover',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='delay',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
